CREATE TABLE t_mottu_cargo (
    id_cargo BIGINT IDENTITY(1,1) PRIMARY KEY,
    nome_cargo VARCHAR(20) NOT NULL,
    CONSTRAINT chk_nome_cargo CHECK (nome_cargo IN (
       'ADMIN','AUXILIAR','CEO','COORDENADOR','ESTAGIARIO',
       'GERENTE','MECANICO','SUPERVISOR'
    ))
);

CREATE TABLE t_mottu_filiais (
    id_filial BIGINT IDENTITY(1,1) PRIMARY KEY,
    end_filial VARCHAR(255) NOT NULL
);

CREATE TABLE t_mottu_motos (
    id_moto BIGINT IDENTITY(1,1) PRIMARY KEY,
    status_moto INT NOT NULL,
    id_filial BIGINT NOT NULL,
    id_imei BIGINT,
    num_motor BIGINT,
    id_qr_code VARCHAR(255),
    modelo_moto VARCHAR(255),
    num_chassi VARCHAR(255),
    placa_moto VARCHAR(255)
);

CREATE TABLE t_mottu_usuario (
    id_usuario BIGINT IDENTITY(1,1) PRIMARY KEY,
    idade INT NOT NULL,
    id_filial BIGINT NOT NULL,
    senha VARCHAR(60) NOT NULL,
    primeiro_nome VARCHAR(50) NOT NULL,
    sobrenome VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE t_usuario_cargo (
    id_cargo BIGINT NOT NULL,
    id_usuario BIGINT NOT NULL,
    PRIMARY KEY (id_cargo, id_usuario)
);

CREATE TABLE t_mottu_localizacoes (
    id_localizacao BIGINT IDENTITY(1,1) PRIMARY KEY,
    pos_x DECIMAL(4,3) NOT NULL,
    pos_y DECIMAL(4,3) NOT NULL,
    status_localizacao INT NOT NULL,
    data_localizacao DATETIME2(6) NOT NULL,
    id_moto BIGINT,
    id_imagem VARCHAR(255) NOT NULL
);

CREATE TABLE t_mottu_arquivo (
    ID_ARQUIVO BIGINT IDENTITY(1,1) PRIMARY KEY,
    ID_SQUARE VARCHAR(255) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    PREFIXO VARCHAR(255),
    URL VARCHAR(500) NOT NULL,
    HASH_SEGURANCA BIT,
    TAMANHO_BYTES BIGINT,
    STATUS_UPLOAD VARCHAR(10) NOT NULL,
    STATUS_ARQUIVO VARCHAR(10) NOT NULL,
    DATA_EXPIRACAO DATETIME2(6),
    AUTO_DOWNLOAD BIT,
    CRIADO_EM DATETIME2(6) NOT NULL DEFAULT SYSDATETIME(),
    ATUALIZADO_EM DATETIME2(6) NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT CHK_STATUS_UPLOAD CHECK (STATUS_UPLOAD IN ('SUCCESS', 'ERROR')),
    CONSTRAINT CHK_STATUS_ARQUIVO CHECK (STATUS_ARQUIVO IN ('ATIVO', 'EXCLUIDO')),
    CONSTRAINT CHK_EXPIRE_VALIDADE CHECK (
        DATA_EXPIRACAO IS NULL OR DATA_EXPIRACAO BETWEEN SYSDATETIME() AND DATEADD(DAY, 365, SYSDATETIME())
    )
);


